import { Topic, Region } from "./types";

export const MARKETS: Region[] = [
  { id: "mx", name: "México", flag: "🇲🇽", type: "country", language: "es", timezone: "America/Mexico_City" },
  { id: "cl", name: "Chile", flag: "🇨🇱", type: "country", language: "es", timezone: "America/Santiago" },
  { id: "ar", name: "Argentina", flag: "🇦🇷", type: "country", language: "es", timezone: "America/Buenos_Aires" },
  { id: "co", name: "Colombia", flag: "🇨🇴", type: "country", language: "es", timezone: "America/Bogota" },
  { id: "pe", name: "Perú", flag: "🇵🇪", type: "country", language: "es", timezone: "America/Lima" },
  { id: "us_hispanic", name: "US Hispanic", flag: "🇺🇸", type: "cultural_cluster", language: "es", timezone: "America/New_York" },
  { id: "latam", name: "LatAm", flag: "🌎", type: "cultural_cluster", language: "es" },
  { id: "global_es", name: "Global Español", flag: "🌐", type: "cultural_cluster", language: "es" },
];

export const MOCK_TOPICS: Topic[] = [
  {
    id: "topic-1",
    title: "México ya clasificó al Mundial, pero aún puede cambiar su camino",
    summary: "La selección mexicana aseguró su lugar en el Mundial 2026, pero los partidos restantes definirán su posición en el grupo y sus rivales en la siguiente ronda.",
    origin_region_id: "mx",
    origin_city: "Ciudad de México",
    category_tag: "Deportes",
    published_at: "2026-06-23T08:00:00Z",
    monetization_risk: "low",
    suggested_format: "Análisis / Opinión",
    suggested_duration: "8–12 min",
    platform: "Both",
    thumbnail_concept: "Selección mexicana celebrando + '¿Y ahora qué?' en texto grande",
    is_cross_border: true,
    cross_border_from: "mx",
    cross_border_to: ["us_hispanic", "latam"],
    sources: [
      { name: "ESPN Deportes", url: "#", published_at: "2026-06-23T07:30:00Z" },
      { name: "MARCA", url: "#", published_at: "2026-06-23T07:45:00Z" },
      { name: "Récord", url: "#", published_at: "2026-06-23T08:00:00Z" },
    ],
    market_scores: {
      mx: { topic_id: "topic-1", market_id: "mx", trend_score: 98, editorial_score: 94, revenue_score: 90, geo_score: 99, master_score: 96, category: "A" },
      us_hispanic: { topic_id: "topic-1", market_id: "us_hispanic", trend_score: 88, editorial_score: 91, revenue_score: 85, geo_score: 93, master_score: 90, category: "A" },
      cl: { topic_id: "topic-1", market_id: "cl", trend_score: 70, editorial_score: 72, revenue_score: 68, geo_score: 75, master_score: 72, category: "B" },
      ar: { topic_id: "topic-1", market_id: "ar", trend_score: 65, editorial_score: 70, revenue_score: 65, geo_score: 70, master_score: 68, category: "B" },
      co: { topic_id: "topic-1", market_id: "co", trend_score: 75, editorial_score: 78, revenue_score: 72, geo_score: 80, master_score: 76, category: "B" },
      pe: { topic_id: "topic-1", market_id: "pe", trend_score: 68, editorial_score: 70, revenue_score: 66, geo_score: 72, master_score: 70, category: "B" },
      latam: { topic_id: "topic-1", market_id: "latam", trend_score: 82, editorial_score: 84, revenue_score: 78, geo_score: 86, master_score: 83, category: "A" },
      global_es: { topic_id: "topic-1", market_id: "global_es", trend_score: 78, editorial_score: 80, revenue_score: 74, geo_score: 76, master_score: 78, category: "B" },
    },
    geo: [
      { topic_id: "topic-1", origin_region_id: "mx", relevance_region_id: "mx", relevance_score: 99, reason: "País de origen, equipo local" },
      { topic_id: "topic-1", origin_region_id: "mx", relevance_region_id: "us_hispanic", relevance_score: 93, reason: "Diáspora mexicana masiva en EEUU, identidad cultural fuerte" },
      { topic_id: "topic-1", origin_region_id: "mx", relevance_region_id: "latam", relevance_score: 86, reason: "Interés regional por el Mundial, México como potencia de la región" },
    ],
    angles: {
      mx: "Lo que todavía se juega México: ¿con quién quieres cruzarte?",
      us_hispanic: "¿El Tri puede llegar lejos? El análisis que todo mexicoamericano necesita ver",
      cl: "El análisis del grupo: cómo afecta la clasificación mexicana al cuadro",
      ar: "El camino de México al Mundial: lo que dice del fútbol latinoamericano",
      latam: "El anfitrión que ya clasificó, pero aún tiene presión",
      co: "México clasificado: cómo cambia el panorama del grupo",
      pe: "La posición de México en el Mundial: todo lo que hay que saber",
    },
    hooks: {
      mx: "México ya está en el Mundial... pero este partido todavía importa mucho",
      us_hispanic: "The Tri is in — but here's why the next game still matters",
      latam: "Ya clasificó, pero el verdadero reto apenas empieza",
    },
  },
  {
    id: "topic-2",
    title: "Chile aprueba nueva ley de 40 horas: qué cambia y qué no",
    summary: "El Congreso chileno aprobó la reducción de la jornada laboral a 40 horas semanales. El debate sobre sus efectos en la economía y el empleo se extiende a otros países de la región.",
    origin_region_id: "cl",
    origin_city: "Santiago",
    category_tag: "Economía",
    published_at: "2026-06-23T06:30:00Z",
    monetization_risk: "low",
    suggested_format: "Explainer",
    suggested_duration: "6–10 min",
    platform: "YouTube",
    thumbnail_concept: "Reloj marcando 40h + '¿Y tu trabajo?' como gancho",
    is_cross_border: true,
    cross_border_from: "cl",
    cross_border_to: ["ar", "mx"],
    sources: [
      { name: "La Tercera", url: "#", published_at: "2026-06-23T06:00:00Z" },
      { name: "El Mercurio", url: "#", published_at: "2026-06-23T06:15:00Z" },
      { name: "CNN Chile", url: "#", published_at: "2026-06-23T06:30:00Z" },
    ],
    market_scores: {
      mx: { topic_id: "topic-2", market_id: "mx", trend_score: 72, editorial_score: 75, revenue_score: 70, geo_score: 75, master_score: 74, category: "B" },
      cl: { topic_id: "topic-2", market_id: "cl", trend_score: 97, editorial_score: 92, revenue_score: 88, geo_score: 96, master_score: 94, category: "A" },
      ar: { topic_id: "topic-2", market_id: "ar", trend_score: 80, editorial_score: 84, revenue_score: 78, geo_score: 83, master_score: 82, category: "A" },
      co: { topic_id: "topic-2", market_id: "co", trend_score: 70, editorial_score: 73, revenue_score: 68, geo_score: 72, master_score: 71, category: "B" },
      pe: { topic_id: "topic-2", market_id: "pe", trend_score: 68, editorial_score: 71, revenue_score: 66, geo_score: 70, master_score: 69, category: "B" },
      us_hispanic: { topic_id: "topic-2", market_id: "us_hispanic", trend_score: 55, editorial_score: 60, revenue_score: 58, geo_score: 62, master_score: 59, category: "C" },
      latam: { topic_id: "topic-2", market_id: "latam", trend_score: 76, editorial_score: 79, revenue_score: 74, geo_score: 78, master_score: 77, category: "B" },
      global_es: { topic_id: "topic-2", market_id: "global_es", trend_score: 65, editorial_score: 68, revenue_score: 63, geo_score: 66, master_score: 66, category: "C" },
    },
    geo: [
      { topic_id: "topic-2", origin_region_id: "cl", relevance_region_id: "cl", relevance_score: 96, reason: "País de origen, cambio legislativo directo" },
      { topic_id: "topic-2", origin_region_id: "cl", relevance_region_id: "ar", relevance_score: 83, reason: "Debate similar en Argentina, alta proximidad cultural" },
      { topic_id: "topic-2", origin_region_id: "cl", relevance_region_id: "mx", relevance_score: 75, reason: "Ángulo: ¿podría pasar en México? Debate laboral activo" },
    ],
    angles: {
      cl: "Todo lo que cambia con las 40 horas: lo que nadie te está contando",
      ar: "Chile lo hizo: ¿cuándo llega esa ley a Argentina?",
      mx: "Chile redujo la semana laboral. ¿Por qué México no puede?",
      latam: "La ley que está cambiando el trabajo en América Latina",
    },
    hooks: {
      cl: "Aprobaron las 40 horas. Esto es lo que realmente cambia para ti",
      ar: "Chile acaba de hacer lo que Argentina lleva años discutiendo",
      mx: "En Chile ya trabajan menos. ¿Y nosotros?",
    },
  },
  {
    id: "topic-3",
    title: "Messi se lesiona en el Inter Miami: ¿peligra su participación en la Copa?",
    summary: "Leo Messi salió lesionado del último partido del Inter Miami. Los médicos evalúan el alcance de la lesión y si podrá recuperarse a tiempo para el próximo torneo.",
    origin_region_id: "us_hispanic",
    origin_city: "Miami",
    category_tag: "Deportes",
    published_at: "2026-06-23T10:00:00Z",
    monetization_risk: "low",
    suggested_format: "Breaking News + Análisis",
    suggested_duration: "5–8 min",
    platform: "Both",
    thumbnail_concept: "Messi saliendo con muletas + '¿Cuándo vuelve?' en rojo",
    is_cross_border: false,
    sources: [
      { name: "TyC Sports", url: "#", published_at: "2026-06-23T09:30:00Z" },
      { name: "Infobae", url: "#", published_at: "2026-06-23T09:45:00Z" },
      { name: "ESPN", url: "#", published_at: "2026-06-23T10:00:00Z" },
      { name: "Clarin", url: "#", published_at: "2026-06-23T10:10:00Z" },
    ],
    market_scores: {
      mx: { topic_id: "topic-3", market_id: "mx", trend_score: 88, editorial_score: 86, revenue_score: 85, geo_score: 87, master_score: 87, category: "A" },
      cl: { topic_id: "topic-3", market_id: "cl", trend_score: 90, editorial_score: 89, revenue_score: 87, geo_score: 92, master_score: 90, category: "A" },
      ar: { topic_id: "topic-3", market_id: "ar", trend_score: 99, editorial_score: 97, revenue_score: 95, geo_score: 99, master_score: 98, category: "A" },
      co: { topic_id: "topic-3", market_id: "co", trend_score: 86, editorial_score: 85, revenue_score: 83, geo_score: 88, master_score: 86, category: "A" },
      pe: { topic_id: "topic-3", market_id: "pe", trend_score: 84, editorial_score: 83, revenue_score: 81, geo_score: 86, master_score: 84, category: "A" },
      us_hispanic: { topic_id: "topic-3", market_id: "us_hispanic", trend_score: 90, editorial_score: 88, revenue_score: 87, geo_score: 89, master_score: 89, category: "A" },
      latam: { topic_id: "topic-3", market_id: "latam", trend_score: 92, editorial_score: 90, revenue_score: 88, geo_score: 92, master_score: 91, category: "A" },
      global_es: { topic_id: "topic-3", market_id: "global_es", trend_score: 91, editorial_score: 89, revenue_score: 87, geo_score: 88, master_score: 89, category: "A" },
    },
    geo: [
      { topic_id: "topic-3", origin_region_id: "us_hispanic", relevance_region_id: "ar", relevance_score: 99, reason: "Messi es argentino, máxima relevancia emocional" },
      { topic_id: "topic-3", origin_region_id: "us_hispanic", relevance_region_id: "latam", relevance_score: 92, reason: "Figura global del fútbol latinoamericano" },
      { topic_id: "topic-3", origin_region_id: "us_hispanic", relevance_region_id: "us_hispanic", relevance_score: 89, reason: "Juega en Miami, interés directo de la comunidad" },
    ],
    angles: {
      ar: "La lesión de Messi: ¿qué dice el médico y cuánto tiempo podría perderse?",
      mx: "Messi lesionado: ¿cómo afecta esto a los planes del Inter Miami y la Copa?",
      cl: "El parte médico de Messi y lo que significa para el fútbol regional",
      us_hispanic: "Messi injured: what we know and what comes next for Inter Miami",
      latam: "La noticia que nadie quería: Messi sale lesionado, cronología completa",
    },
    hooks: {
      ar: "Messi salió con muletas. Esto es todo lo que sabemos hasta ahora",
      mx: "Messi lesionado: el peor momento para el Inter Miami",
      latam: "Cayó Messi. Cronología completa de lo que pasó",
    },
  },
  {
    id: "topic-4",
    title: "Dólar en Argentina rompe nuevo récord: lo que viene para la economía",
    summary: "El tipo de cambio en Argentina alcanzó un nuevo máximo histórico, generando tensión en los mercados y debate sobre la política económica del gobierno de Milei.",
    origin_region_id: "ar",
    origin_city: "Buenos Aires",
    category_tag: "Economía",
    published_at: "2026-06-23T09:00:00Z",
    monetization_risk: "medium",
    suggested_format: "Explainer urgente",
    suggested_duration: "7–10 min",
    platform: "YouTube",
    thumbnail_concept: "Billete de dólar + flecha roja hacia arriba + '¿Qué sigue?'",
    is_cross_border: true,
    cross_border_from: "ar",
    cross_border_to: ["latam", "global_es"],
    sources: [
      { name: "Infobae", url: "#", published_at: "2026-06-23T08:30:00Z" },
      { name: "La Nación", url: "#", published_at: "2026-06-23T08:45:00Z" },
      { name: "Clarín", url: "#", published_at: "2026-06-23T09:00:00Z" },
    ],
    market_scores: {
      mx: { topic_id: "topic-4", market_id: "mx", trend_score: 60, editorial_score: 64, revenue_score: 58, geo_score: 62, master_score: 61, category: "C" },
      cl: { topic_id: "topic-4", market_id: "cl", trend_score: 72, editorial_score: 74, revenue_score: 68, geo_score: 75, master_score: 73, category: "B" },
      ar: { topic_id: "topic-4", market_id: "ar", trend_score: 98, editorial_score: 94, revenue_score: 80, geo_score: 97, master_score: 93, category: "A" },
      co: { topic_id: "topic-4", market_id: "co", trend_score: 65, editorial_score: 68, revenue_score: 63, geo_score: 67, master_score: 66, category: "C" },
      pe: { topic_id: "topic-4", market_id: "pe", trend_score: 62, editorial_score: 65, revenue_score: 60, geo_score: 64, master_score: 63, category: "C" },
      us_hispanic: { topic_id: "topic-4", market_id: "us_hispanic", trend_score: 70, editorial_score: 72, revenue_score: 65, geo_score: 74, master_score: 70, category: "B" },
      latam: { topic_id: "topic-4", market_id: "latam", trend_score: 80, editorial_score: 82, revenue_score: 74, geo_score: 82, master_score: 80, category: "A" },
      global_es: { topic_id: "topic-4", market_id: "global_es", trend_score: 76, editorial_score: 78, revenue_score: 70, geo_score: 78, master_score: 76, category: "B" },
    },
    geo: [
      { topic_id: "topic-4", origin_region_id: "ar", relevance_region_id: "ar", relevance_score: 97, reason: "País de origen, crisis monetaria directa" },
      { topic_id: "topic-4", origin_region_id: "ar", relevance_region_id: "latam", relevance_score: 82, reason: "Argentina como barómetro económico de la región" },
      { topic_id: "topic-4", origin_region_id: "ar", relevance_region_id: "cl", relevance_score: 75, reason: "Alta integración comercial, referente cercano" },
    ],
    angles: {
      ar: "El dólar rompe récord: qué significa para tu bolsillo y qué hacer",
      cl: "Argentina en crisis cambiaria: ¿puede contagiar a Chile?",
      latam: "El dólar argentino se dispara: señales de alerta para toda la región",
      us_hispanic: "Argentina's dollar crisis explained: what's happening and why it matters",
    },
    hooks: {
      ar: "El dólar rompió el récord histórico. Lo que nadie te dijo sobre lo que viene",
      cl: "Lo que está pasando en Argentina debería preocuparte",
      latam: "Nueva crisis en Argentina: cronología y lo que viene",
    },
  },
  {
    id: "topic-5",
    title: "Colombia derrota a Brasil en eliminatoria: la sorpresa del mes",
    summary: "La selección colombiana consiguió una victoria histórica ante Brasil en las eliminatorias sudamericanas, reavivando las esperanzas del equipo cafetero para el Mundial.",
    origin_region_id: "co",
    origin_city: "Bogotá",
    category_tag: "Deportes",
    published_at: "2026-06-23T07:00:00Z",
    monetization_risk: "low",
    suggested_format: "Análisis táctico + reacciones",
    suggested_duration: "10–15 min",
    platform: "Both",
    thumbnail_concept: "Jugador colombiano celebrando + 'Histórico' en amarillo",
    is_cross_border: true,
    cross_border_from: "co",
    cross_border_to: ["latam", "us_hispanic"],
    sources: [
      { name: "El Tiempo", url: "#", published_at: "2026-06-23T06:30:00Z" },
      { name: "Win Sports", url: "#", published_at: "2026-06-23T06:45:00Z" },
      { name: "ESPN Latinoamérica", url: "#", published_at: "2026-06-23T07:00:00Z" },
    ],
    market_scores: {
      mx: { topic_id: "topic-5", market_id: "mx", trend_score: 75, editorial_score: 76, revenue_score: 72, geo_score: 74, master_score: 74, category: "B" },
      cl: { topic_id: "topic-5", market_id: "cl", trend_score: 78, editorial_score: 79, revenue_score: 75, geo_score: 80, master_score: 78, category: "B" },
      ar: { topic_id: "topic-5", market_id: "ar", trend_score: 80, editorial_score: 81, revenue_score: 77, geo_score: 83, master_score: 80, category: "A" },
      co: { topic_id: "topic-5", market_id: "co", trend_score: 97, editorial_score: 95, revenue_score: 92, geo_score: 96, master_score: 95, category: "A" },
      pe: { topic_id: "topic-5", market_id: "pe", trend_score: 76, editorial_score: 77, revenue_score: 73, geo_score: 78, master_score: 76, category: "B" },
      us_hispanic: { topic_id: "topic-5", market_id: "us_hispanic", trend_score: 80, editorial_score: 81, revenue_score: 78, geo_score: 82, master_score: 80, category: "A" },
      latam: { topic_id: "topic-5", market_id: "latam", trend_score: 88, editorial_score: 87, revenue_score: 84, geo_score: 89, master_score: 87, category: "A" },
      global_es: { topic_id: "topic-5", market_id: "global_es", trend_score: 82, editorial_score: 83, revenue_score: 79, geo_score: 82, master_score: 82, category: "A" },
    },
    geo: [
      { topic_id: "topic-5", origin_region_id: "co", relevance_region_id: "co", relevance_score: 96, reason: "Victoria histórica del equipo nacional" },
      { topic_id: "topic-5", origin_region_id: "co", relevance_region_id: "latam", relevance_score: 89, reason: "Brasil como referente regional; derrota genera alto interés" },
      { topic_id: "topic-5", origin_region_id: "co", relevance_region_id: "ar", relevance_score: 83, reason: "Competencia directa en eliminatorias, alta atención al resultado" },
    ],
    angles: {
      co: "Colombia le ganó a Brasil: el análisis que todos necesitan ver",
      ar: "Colombia derrotó a Brasil: qué dice de la eliminatoria y las posiciones",
      latam: "El resultado que nadie esperaba: Colombia vence a Brasil",
      us_hispanic: "Colombia upsets Brazil: what this means for Copa qualifiers",
    },
    hooks: {
      co: "Le ganamos a Brasil. Y así fue, gol a gol",
      ar: "Colombia venció a Brasil. ¿Qué pasa ahora con la tabla?",
      latam: "Cayó Brasil. Colombia hizo historia esta noche",
    },
  },
  {
    id: "topic-6",
    title: "Terremoto 6.2 en Lima: daños y situación actual",
    summary: "Un sismo de magnitud 6.2 sacudió la ciudad de Lima. Las autoridades reportan daños en infraestructura y evalúan el número de afectados.",
    origin_region_id: "pe",
    origin_city: "Lima",
    category_tag: "Emergencias",
    published_at: "2026-06-23T05:00:00Z",
    monetization_risk: "high",
    suggested_format: "Breaking News",
    suggested_duration: "5–7 min",
    platform: "Facebook",
    thumbnail_concept: "Mapa de Lima + ondas sísmicas + 'Sismo en vivo'",
    is_cross_border: false,
    sources: [
      { name: "RPP Noticias", url: "#", published_at: "2026-06-23T04:45:00Z" },
      { name: "El Comercio", url: "#", published_at: "2026-06-23T05:00:00Z" },
      { name: "América Noticias", url: "#", published_at: "2026-06-23T05:15:00Z" },
    ],
    market_scores: {
      mx: { topic_id: "topic-6", market_id: "mx", trend_score: 65, editorial_score: 62, revenue_score: 40, geo_score: 60, master_score: 58, category: "C" },
      cl: { topic_id: "topic-6", market_id: "cl", trend_score: 72, editorial_score: 68, revenue_score: 45, geo_score: 70, master_score: 65, category: "C" },
      ar: { topic_id: "topic-6", market_id: "ar", trend_score: 60, editorial_score: 58, revenue_score: 38, geo_score: 56, master_score: 54, category: "C" },
      co: { topic_id: "topic-6", market_id: "co", trend_score: 70, editorial_score: 67, revenue_score: 43, geo_score: 68, master_score: 63, category: "C" },
      pe: { topic_id: "topic-6", market_id: "pe", trend_score: 99, editorial_score: 95, revenue_score: 50, geo_score: 98, master_score: 88, category: "A" },
      us_hispanic: { topic_id: "topic-6", market_id: "us_hispanic", trend_score: 68, editorial_score: 65, revenue_score: 42, geo_score: 66, master_score: 62, category: "C" },
      latam: { topic_id: "topic-6", market_id: "latam", trend_score: 75, editorial_score: 70, revenue_score: 46, geo_score: 73, master_score: 68, category: "B" },
      global_es: { topic_id: "topic-6", market_id: "global_es", trend_score: 68, editorial_score: 63, revenue_score: 40, geo_score: 65, master_score: 61, category: "C" },
    },
    geo: [
      { topic_id: "topic-6", origin_region_id: "pe", relevance_region_id: "pe", relevance_score: 98, reason: "Epicentro en Lima, emergencia nacional" },
      { topic_id: "topic-6", origin_region_id: "pe", relevance_region_id: "latam", relevance_score: 73, reason: "Interés regional por emergencias sísmicas" },
    ],
    angles: {
      pe: "Terremoto en Lima: situación en tiempo real y cómo ayudar",
      cl: "Sismo en Lima: qué pasó y qué está haciendo el gobierno peruano",
      latam: "Lima temblor 6.2: cronología completa y situación actual",
    },
    hooks: {
      pe: "Terremoto en Lima ahora mismo. Todo lo que sabemos",
      cl: "Tembló Lima. Estos son los daños reportados",
      latam: "Sismo 6.2 en Lima: sigue la cobertura en vivo",
    },
  },
];
