import {
  HeatmapMoment,
  StoryAnalysis,
  TranscriptSegment,
  VideoSource,
} from "@/lib/chacotero/types";
import { CandidateSegment } from "@/lib/chacotero/story-selection";

// Fictional demo case. Any resemblance to real callers or hosts is
// coincidental — this exists purely to exercise the editing flow end to end.
export const DEMO_VIDEO_ID = "wemul-demo-001";

export const DEMO_VIDEO_SOURCE: VideoSource = {
  url: `https://www.youtube.com/watch?v=${DEMO_VIDEO_ID}`,
  title: "EL CHACOTERO SENTIMENTAL — \"Mi mejor amiga y mi pololo me traicionaron\"",
  channelName: "El Chacotero Sentimental",
  thumbnailUrl: "/chacotero-demo-thumb.svg",
  durationSeconds: 918,
  publishedAt: "2026-05-14T02:00:00Z",
  sourceType: "youtube",
};

export const DEMO_TRANSCRIPT: TranscriptSegment[] = [
  { id: "t0", speaker: "Conductor", startSeconds: 0, endSeconds: 18, confidence: 0.97,
    text: "Bienvenidos de nuevo. Hoy tenemos un llamado que parte fuerte: 'pensé que mi mejor amiga era mi mejor amiga, hasta que encontré los mensajes en el celular de mi pololo'. Vamos a esa llamada." },
  { id: "t1", speaker: "Conductor", startSeconds: 18, endSeconds: 34, confidence: 0.96,
    text: "¿Cómo estái? ¿Con quién hablamos?" },
  { id: "t2", speaker: "Marcela", startSeconds: 34, endSeconds: 58, confidence: 0.95,
    text: "Hola, buenas noches. Soy la Marcela, tengo 29 años, llamo desde Rancagua." },
  { id: "t3", speaker: "Conductor", startSeconds: 58, endSeconds: 70, confidence: 0.96,
    text: "Cuéntanos qué pasó, tranquila que aquí somos puro cariño." },
  { id: "t4", speaker: "Marcela", startSeconds: 70, endSeconds: 118, confidence: 0.94,
    text: "Mira, yo llevo tres años con el Fabrizio, mi pololo. Vivimos juntos hace como un año y medio. Todo súper bien, la relación más estable que he tenido." },
  { id: "t5", speaker: "Marcela", startSeconds: 118, endSeconds: 150, confidence: 0.93,
    text: "Y mi mejor amiga es la Susy. La conozco desde el colegio, ella fue mi dama de honor cuando me casé la primera vez. O sea, es como mi hermana." },
  { id: "t6", speaker: "Marcela", startSeconds: 150, endSeconds: 178, confidence: 0.93,
    text: "El problema es que hace como un mes empecé a notar al Fabrizio raro, como ausente, cuidando mucho el celular." },
  { id: "t7", speaker: "Marcela", startSeconds: 178, endSeconds: 205, confidence: 0.92,
    text: "Un día se quedó dormido en el sillón y el celular quedó desbloqueado, y me saltó una notificación de WhatsApp." },
  { id: "t8", speaker: "Marcela", startSeconds: 205, endSeconds: 232, confidence: 0.91,
    text: "Era de un contacto que decía 'S ❤', y decía: 'te extraño, ojalá pudiéramos vernos como el jueves pasado'." },
  { id: "t9", speaker: "Marcela", startSeconds: 232, endSeconds: 260, confidence: 0.92,
    text: "Ahí quedé fría, pero seguí leyendo. Eran meses de conversación, cosas súper cariñosas, buenos días, buenas noches." },
  { id: "t10", speaker: "Conductor", startSeconds: 260, endSeconds: 275, confidence: 0.95,
    text: "¿Y tú cachabai quién era la tal 'S'?" },
  { id: "t11", speaker: "Marcela", startSeconds: 275, endSeconds: 300, confidence: 0.91,
    text: "No al tiro. Pensé mil personas, pero algo me decía que tenía que ver con la Susy." },
  { id: "t12", speaker: "Marcela", startSeconds: 300, endSeconds: 330, confidence: 0.92,
    text: "Al otro día lo enfrenté, le dije 'quién es S', y él me dijo que era una compañera de la pega, que no me preocupara." },
  { id: "t13", speaker: "Marcela", startSeconds: 330, endSeconds: 360, confidence: 0.9,
    text: "Le creí como una tonta, pero igual seguí mirando el celular cuando podía." },
  { id: "t14", speaker: "Marcela", startSeconds: 360, endSeconds: 395, confidence: 0.91,
    text: "Y ahí encontré fotos, capturas de hace ocho meses atrás. O sea, esto no era nuevo, poh." },
  { id: "t15", speaker: "Marcela", startSeconds: 395, endSeconds: 420, confidence: 0.92,
    text: "Decidí hablar directo con la Susy. La llamé, le pregunté de frente." },
  { id: "t16", speaker: "Marcela", startSeconds: 420, endSeconds: 450, confidence: 0.9,
    text: "Ella se puso rara, empezó a tartamudear, me dijo que yo estaba loca, que cómo se me ocurría." },
  { id: "t17", speaker: "Marcela", startSeconds: 450, endSeconds: 490, confidence: 0.93,
    text: "Pero esa misma noche una amiga en común me manda la captura de una conversación de la Susy con otra amiga, donde contaba todo." },
  { id: "t18", speaker: "Marcela", startSeconds: 490, endSeconds: 535, confidence: 0.94,
    text: "Ahí supe que llevaban ocho meses viéndose a escondidas, en la casa de la Susy, cuando yo estaba de turno de noche en el hospital." },
  { id: "t19", speaker: "Conductor", startSeconds: 535, endSeconds: 555, confidence: 0.96,
    text: "Oye, ocho meses es hartísimo tiempo. ¿Cómo tomaste esa parte?" },
  { id: "t20", speaker: "Marcela", startSeconds: 555, endSeconds: 585, confidence: 0.91,
    text: "Me quería morir, pero dije 'no más, esto se acaba ahora', así que planifiqué enfrentarlos a los dos juntos." },
  { id: "t21", speaker: "Marcela", startSeconds: 585, endSeconds: 615, confidence: 0.91,
    text: "Aproveché el cumpleaños de mi suegra, donde iban a estar los dos, toda la familia." },
  { id: "t22", speaker: "Marcela", startSeconds: 615, endSeconds: 650, confidence: 0.9,
    text: "Ahí, delante de todos, empecé a hacer preguntas. Primero suaves, después directas." },
  { id: "t23", speaker: "Marcela", startSeconds: 650, endSeconds: 690, confidence: 0.9,
    text: "Y en eso la Susy, para defenderse, suelta que ella le había prestado plata al Fabrizio hace meses y que por eso 'se debían tanto'." },
  { id: "t24", speaker: "Marcela", startSeconds: 690, endSeconds: 715, confidence: 0.89,
    text: "Ahí quedé más perdida todavía: plata, mentiras, meses, la traición completa." },
  { id: "t25", speaker: "Marcela", startSeconds: 715, endSeconds: 760, confidence: 0.88,
    text: "Se armó tremendo escándalo. Mi suegra llorando, mi cuñado tratando de separar, y yo grité que se fueran los dos de mi vista." },
  { id: "t26", speaker: "Marcela", startSeconds: 760, endSeconds: 790, confidence: 0.92,
    text: "Al final terminé con el Fabrizio esa misma noche, y no he vuelto a hablar con la Susy desde entonces." },
  { id: "t27", speaker: "Marcela", startSeconds: 790, endSeconds: 815, confidence: 0.93,
    text: "Aprendí que hay que hacerle caso al estómago cuando algo anda raro, y que la confianza ciega también es un error mío." },
  { id: "t28", speaker: "Conductor", startSeconds: 815, endSeconds: 870, confidence: 0.97,
    text: "Mira Marcela, primero, tranquila: esto habla bien de ti, que enfrentaste con la verdad por delante. Segundo... plata y amor mezclados con la mejor amiga es la combinación más peligrosa que existe. Uno puede perdonar una traición, pero dos juntas, difícil. Te mandamos un abrazo grande, y ojalá el próximo amor te llegue sin condiciones, ni de la Susy ni de nadie." },
  { id: "t29", speaker: "Conductor", startSeconds: 870, endSeconds: 895, confidence: 0.96,
    text: "Esto fue El Chacotero. Seguimos después de la pausa con otro llamado que promete." },
];

export const DEMO_HEATMAP_MOMENTS: HeatmapMoment[] = [
  { startSeconds: 205, endSeconds: 232, intensity: 0.55, label: "Momento del mensaje 'S ❤'" },
  { startSeconds: 490, endSeconds: 530, intensity: 0.78, label: "Confirmación de los 8 meses" },
  { startSeconds: 655, endSeconds: 690, intensity: 0.82, label: "Revelación del dinero" },
  { startSeconds: 715, endSeconds: 755, intensity: 0.95, label: "Escándalo en el cumpleaños" },
  { startSeconds: 828, endSeconds: 858, intensity: 0.68, label: "Frase del conductor sobre la traición doble" },
];

export const DEMO_STORY_ANALYSIS_BASE: Omit<StoryAnalysis, "editorialSummary" | "continuityWarnings"> = {
  suggestedTitle: "La Susy, mi mejor amiga… y la traición de los ocho meses",
  premise: "Marcela descubre que su pololo de tres años y su mejor amiga de toda la vida llevaban ocho meses viéndose a escondidas.",
  conflictType: "Infidelidad y traición de amistad",
  identifiedCharacters: [
    "Marcela — protagonista, 29 años, llama desde Rancagua",
    "Fabrizio — pololo de Marcela hace 3 años",
    "Susy — mejor amiga de Marcela desde el colegio",
  ],
  relationships: [
    "Marcela y Fabrizio: pareja hace 3 años, conviven hace 1 año y medio",
    "Marcela y Susy: mejores amigas desde el colegio, ex dama de honor",
    "Fabrizio y Susy: encuentros secretos durante 8 meses",
  ],
  tone: ["Dramático", "Confesional", "Con humor en el remate"],
  mainConflict: "Marcela descubre mensajes en el celular de Fabrizio que revelan una relación paralela con su mejor amiga Susy.",
  turningPoint: "Una amiga en común le envía la prueba de que Fabrizio y Susy llevan ocho meses encontrándose a escondidas.",
  climax: "En el cumpleaños de su suegra, Marcela enfrenta a ambos frente a toda la familia y Susy revela además que le prestó dinero a Fabrizio.",
  ending: "Marcela termina con Fabrizio esa misma noche y corta la amistad con Susy; se queda con el aprendizaje de confiar en su intuición.",
};

// Candidate beats the narrative engine can pick from. Durations are edited
// excerpts (not full raw transcript lines) — an editor rarely uses an entire
// verbatim answer, only the tightest span that carries the beat.
export const DEMO_CANDIDATES: CandidateSegment[] = [
  {
    id: "b1-hook",
    category: "hook",
    tier: 1,
    startSeconds: 2,
    endSeconds: 18,
    transcript: "\"Pensé que mi mejor amiga era mi mejor amiga, hasta que encontré los mensajes en el celular de mi pololo.\"",
    editorialReason: "Frase que instala de inmediato el conflicto central: la traición de la mejor amiga.",
    narrativeScore: 94,
    emotionalScore: 82,
    clarityScore: 90,
    audienceInterestScore: 88,
    alternatives: [
      {
        id: "b1-alt-a",
        startSeconds: 0,
        endSeconds: 34,
        transcript: "Incluye el saludo completo del conductor antes de dar paso a la llamada.",
        editorialReason: "Más cálido y natural, pero menos directo — tarda más en instalar el conflicto.",
        narrativeScore: 85,
      },
      {
        id: "b1-alt-b",
        startSeconds: 205,
        endSeconds: 232,
        transcript: "\"Era de un contacto que decía 'S ❤': 'te extraño, ojalá pudiéramos vernos como el jueves pasado'.\"",
        editorialReason: "Más específico y crudo, pero requiere haber escuchado el contexto previo para entenderse solo.",
        narrativeScore: 80,
      },
    ],
  },
  {
    id: "b2-context-who",
    category: "context",
    tier: 1,
    startSeconds: 40,
    endSeconds: 56,
    transcript: "\"Soy la Marcela, tengo 29 años, llamo desde Rancagua.\"",
    editorialReason: "Identifica a la llamante lo mínimo indispensable para poder seguir su historia.",
    narrativeScore: 65,
    emotionalScore: 30,
    clarityScore: 95,
    audienceInterestScore: 35,
  },
  {
    id: "b3-context-relationship",
    category: "context",
    tier: 2,
    startSeconds: 70,
    endSeconds: 150,
    transcript: "\"Llevo tres años con el Fabrizio, vivimos juntos hace un año y medio... y mi mejor amiga es la Susy, la conozco desde el colegio, es como mi hermana.\"",
    editorialReason: "Establece los tres años de relación y quién es la Susy, clave para entender la traición.",
    narrativeScore: 80,
    emotionalScore: 45,
    clarityScore: 88,
    audienceInterestScore: 40,
  },
  {
    id: "b4-conflict",
    category: "conflict",
    tier: 1,
    startSeconds: 185,
    endSeconds: 205,
    transcript: "\"Un día se quedó dormido en el sillón y el celular quedó desbloqueado, y me saltó una notificación de WhatsApp.\"",
    editorialReason: "Primer quiebre: el hallazgo del celular desbloqueado de Fabrizio.",
    narrativeScore: 85,
    emotionalScore: 70,
    clarityScore: 85,
    audienceInterestScore: 65,
  },
  {
    id: "b5-escalation-1",
    category: "escalation",
    tier: 2,
    startSeconds: 205,
    endSeconds: 260,
    transcript: "\"El mensaje decía 'te extraño'... seguí leyendo y eran meses de conversación cariñosa.\"",
    editorialReason: "El mensaje flirteante y el descubrimiento de que llevan tiempo escribiéndose.",
    narrativeScore: 74,
    emotionalScore: 68,
    clarityScore: 70,
    audienceInterestScore: 72,
  },
  {
    id: "b6-escalation-2",
    category: "escalation",
    tier: 3,
    startSeconds: 260,
    endSeconds: 300,
    transcript: "\"¿Cachabai quién era la tal 'S'?\" — \"No al tiro, pero algo me decía que tenía que ver con la Susy.\"",
    editorialReason: "La duda sobre quién es 'S', antes de tener certeza.",
    narrativeScore: 58,
    emotionalScore: 50,
    clarityScore: 60,
    audienceInterestScore: 45,
  },
  {
    id: "b7-escalation-3",
    category: "escalation",
    tier: 2,
    startSeconds: 300,
    endSeconds: 360,
    transcript: "\"Lo enfrenté, le dije 'quién es S', y me dijo que era una compañera de trabajo. Le creí, pero seguí mirando el celular.\"",
    editorialReason: "Primera confrontación: Fabrizio miente y ella le cree — muestra el engaño sostenido.",
    narrativeScore: 76,
    emotionalScore: 65,
    clarityScore: 78,
    audienceInterestScore: 60,
  },
  {
    id: "b8-escalation-4",
    category: "escalation",
    tier: 2,
    startSeconds: 360,
    endSeconds: 450,
    transcript: "\"Encontré capturas de hace ocho meses. Llamé a la Susy directo, y ella se puso rara, empezó a tartamudear.\"",
    editorialReason: "El hallazgo de capturas de ocho meses atrás y el llamado directo a la Susy, que se pone a la defensiva.",
    narrativeScore: 79,
    emotionalScore: 72,
    clarityScore: 75,
    audienceInterestScore: 70,
  },
  {
    id: "b9-revelation-1",
    category: "revelation",
    tier: 1,
    startSeconds: 485,
    endSeconds: 530,
    transcript: "\"Una amiga en común me manda la captura de una conversación de la Susy, donde contaba todo. Ahí supe que llevaban ocho meses viéndose a escondidas.\"",
    editorialReason: "La revelación de los ocho meses de encuentros a escondidas: el giro que redefine toda la historia.",
    narrativeScore: 96,
    emotionalScore: 92,
    clarityScore: 82,
    audienceInterestScore: 90,
    alternatives: [
      {
        id: "b9-alt-a",
        startSeconds: 450,
        endSeconds: 535,
        transcript: "Incluye cómo llegó la prueba: \"esa misma noche una amiga en común me manda la captura de una conversación de la Susy con otra amiga, donde contaba todo.\"",
        editorialReason: "Más completa y creíble, muestra cómo llegó la prueba, pero alarga el bloque casi 40 segundos más.",
        narrativeScore: 90,
      },
    ],
  },
  {
    id: "b10-escalation-5",
    category: "escalation",
    tier: 3,
    startSeconds: 535,
    endSeconds: 615,
    transcript: "\"Me quería morir, pero dije 'esto se acaba ahora'. Aproveché el cumpleaños de mi suegra, donde iban a estar los dos.\"",
    editorialReason: "Puente hacia la confrontación: decide enfrentarlos juntos en el cumpleaños familiar.",
    narrativeScore: 60,
    emotionalScore: 62,
    clarityScore: 55,
    audienceInterestScore: 50,
  },
  {
    id: "b11-climax-1",
    category: "climax",
    tier: 1,
    startSeconds: 620,
    endSeconds: 635,
    transcript: "\"Delante de todos, empecé a hacer preguntas. Primero suaves, después directas.\"",
    editorialReason: "Comienza la confrontación frente a toda la familia.",
    narrativeScore: 84,
    emotionalScore: 80,
    clarityScore: 75,
    audienceInterestScore: 78,
  },
  {
    id: "b12-revelation-2",
    category: "revelation",
    tier: 2,
    startSeconds: 650,
    endSeconds: 690,
    transcript: "\"La Susy, para defenderse, suelta que le había prestado plata al Fabrizio hace meses, y que por eso 'se debían tanto'.\"",
    editorialReason: "Giro adicional: la amiga revela que también hay dinero de por medio, agravando la traición.",
    narrativeScore: 88,
    emotionalScore: 85,
    clarityScore: 78,
    audienceInterestScore: 88,
    alternatives: [
      {
        id: "b12-alt-a",
        startSeconds: 650,
        endSeconds: 715,
        transcript: "Incluye la reacción inmediata de Marcela tras enterarse del dinero: \"quedé más perdida todavía\".",
        editorialReason: "Más completa emocionalmente, pero alarga el clímax casi 30 segundos más.",
        narrativeScore: 86,
      },
    ],
  },
  {
    id: "b13-climax-2",
    category: "climax",
    tier: 1,
    startSeconds: 725,
    endSeconds: 760,
    transcript: "\"Se armó tremendo escándalo. Mi suegra llorando, mi cuñado tratando de separar, y yo grité que se fueran los dos de mi vista.\"",
    editorialReason: "El punto más alto: el escándalo estalla frente a toda la familia.",
    narrativeScore: 97,
    emotionalScore: 96,
    clarityScore: 80,
    audienceInterestScore: 93,
  },
  {
    id: "b14-closing",
    category: "closing",
    tier: 1,
    startSeconds: 762,
    endSeconds: 782,
    transcript: "\"Terminé con el Fabrizio esa misma noche y no he vuelto a hablar con la Susy.\"",
    editorialReason: "Cómo terminó todo: cierre comprensible de la historia.",
    narrativeScore: 90,
    emotionalScore: 75,
    clarityScore: 92,
    audienceInterestScore: 65,
  },
  {
    id: "b15-reaction",
    category: "reaction",
    tier: 1,
    startSeconds: 843,
    endSeconds: 868,
    transcript: "\"Uno puede perdonar una traición, pero dos juntas, difícil. Te mandamos un abrazo grande.\"",
    editorialReason: "El remate y consejo del conductor, sello de identidad del programa.",
    narrativeScore: 93,
    emotionalScore: 78,
    clarityScore: 85,
    audienceInterestScore: 85,
    alternatives: [
      {
        id: "b15-alt-a",
        startSeconds: 815,
        endSeconds: 870,
        transcript: "\"Esto habla bien de ti... plata y amor mezclados con la mejor amiga es la combinación más peligrosa que existe. Uno puede perdonar una traición, pero dos juntas, difícil. Te mandamos un abrazo grande.\"",
        editorialReason: "Más cálido y completo, pero casi el doble de largo.",
        narrativeScore: 90,
      },
    ],
  },
  {
    id: "b16-transition",
    category: "transition",
    tier: 3,
    startSeconds: 870,
    endSeconds: 895,
    transcript: "\"Esto fue El Chacotero. Seguimos después de la pausa con otro llamado que promete.\"",
    editorialReason: "Cierre de bloque del programa, sin aporte narrativo al caso.",
    narrativeScore: 35,
    emotionalScore: 20,
    clarityScore: 60,
    audienceInterestScore: 30,
  },
];
